language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  - PACKAGE="charrua-core" OCAML_VERSION=4.01
  - PACKAGE="charrua-core" OCAML_VERSION=latest
  - PACKAGE="charrua-core" OCAML_VERSION=latest
