language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="charrua-core.9999"
  - TESTS=true
  matrix:
  - DISTRO="alpine-3.5" OCAML_VERSION="4.03.0"
  - DISTRO="centos-6" OCAML_VERSION="4.04.1"
  - DISTRO="centos-7" OCAML_VERSION="4.04.0"
  - DISTRO="debian-stable" OCAML_VERSION="4.04.1"
  - DISTRO="debian-testing" OCAML_VERSION="4.03.0"
  - DISTRO="fedora-25" OCAML_VERSION="4.03.0"
  - DISTRO="ubuntu-14.04" OCAML_VERSION="4.03.0"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03.0"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.04.1"
